### ISSUE TITLE
It more question then bug or both

### ISSUE THREAD

**Issue by menesty** [jnr/jnr-ffi#112] opened 2017-03-10 14:56 UTC
I have simple c++ project 
library.h
```c
   #ifndef PRINTER_LIB_LIBRARY_H
   #define PRINTER_LIB_LIBRARY_H
       void* ptr_return_array_element(void **ptrArray, int arrayIndex);
   #endif
```

library.cpp
```cpp
   #include "library.h"
   void* ptr_return_array_element(void **ptrArray, int arrayIndex){
        return ptrArray[arrayIndex];
   }
```

CMakeLists.txt
```
   cmake_minimum_required(VERSION 3.6)
   project(printer_lib)
   set(CMAKE_CXX_STANDARD 11)
   set(SOURCE_FILES library.cpp library.h) 
   add_library(printer_lib SHARED ${SOURCE_FILES})
```
after compilation get
``` 
../printer-lib/cmake-build-debug/libprinter_lib.dylib
```

and have java class

```java
import jnr.ffi.LibraryLoader;
import jnr.ffi.annotations.In;

public class Test {
  public static interface TestLib {
    String ptr_return_array_element(@In String[] array, int index);
  }
  static TestLib testlib;
  public static void main(String... arg) {
    String path = "../c-projects/printer-lib/cmake-build-debug";

    TestLib testlib = LibraryLoader.create(TestLib.class).search(path).load("printer_lib");
    final String MAGIC = "deadbeef";
    System.out.println(testlib.ptr_return_array_element(new String[] { MAGIC }, 0));
  }
}
```

after run I got this error
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: unknown
	at jnr.ffi.provider.jffi.AsmRuntime.newUnsatisifiedLinkError(AsmRuntime.java:40)
	at org.menesty.jnr.Test$TestLib$jnr$ffi$0.ptr_return_array_element(Unknown Source)
	at org.menesty.jnr.Test.main(Test.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

macOs sierra 10.12.3 
XCode Version 8.2.1 (8C1002) 

Can it be problem with compilation of lib ? because when I run test from jnr-ffi project all pass.
Thanks

**Comment by menesty** [comment] 2017-05-24 17:39
it can be of different bit version jdk and your lib

**Comment by xueyumusic** [comment] 2020-03-02 09:59
I met almost the same error. It looks that in `library.cpp` it should use `extern "C"`.

**Comment by Low-power** [comment] 2020-03-26 09:34
Looks like you need to create a C project instead of C++. In your test program, you didn't use any C++ features, so just change your `library.cpp` to `library.c`, and try again.

**Comment by headius** [comment] 2020-03-27 20:02
Yes, try building this as a C project; the JVM uses C++ and it's possible you're getting some conflicting versions of the C++ runtime, or something else about it being C++ is preventing it from loading.

Also, make sure the symbol you want to pull in is actually getting exported by the library using `nm` or equivalent.

**Comment by headius** [comment] 2020-05-12 19:33
Not a bug, hopefully I was able to help... closing!

**Closed by headius** 2020-05-12 19:33 UTC
